# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  catalogwebapi:
    image: catalogwebapi
    build:
      context: .
      dockerfile: Catalog.WebApi/Dockerfile
    ports:
      - 5093:5093
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
